server:
  port: 8877

person:
  name: 张三
  age: 18


#spring:
#  security:
#    user:
#      name: lencho
#      password: 123456
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hadoop104:3306/db01?serverTimezone=GMT%2B8
    username: root
    password: 123456
